services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    command: start-dev --import-realm
    environment:
      DEBUG: 'true'
      DEBUG_PORT: '*:8787'
      KC_LOG_LEVEL: INFO,de.keycloak:debug
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - '8080:8080'
      - '8787:8787'
    volumes:
      - kc-data:/opt/keycloak/data
      - ./src/test/resources/demo-realm.json:/opt/keycloak/data/import/demo-realm.json
      - ./target/keycloak-dev-workshop.jar:/opt/keycloak/providers/keycloak-dev-workshop.jar
volumes:
  kc-data:
    name: keycloak-dev-workshop
